# Generated by Django 3.1.4 on 2020-12-08 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=False, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('group', models.CharField(max_length=50)),
                ('risk', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
